// Package nip43 implements NIP-43: Relay Access Metadata and Requests --
// relay membership lists, roles, and a self-service join/leave/invite
// flow. This package is a pure protocol library (parsing, structural
// validation, and event construction); it has no dependency on relay/.
package nip43

import (
	"errors"
	"fmt"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/ohstr/nmilat/nip01"
	"github.com/ohstr/nmilat/utils"
)

const (
	KindRoleDefinition = 33534
	KindMembershipList = 13534
	KindAddUser        = 8000
	KindRemoveUser     = 8001
	KindJoinRequest    = 28934
	KindInviteRequest  = 28935
	KindLeaveRequest   = 28936
)

// DefaultRequestFreshnessWindow is this package's default tolerance for
// "created_at MUST be now, plus or minus a few minutes" (the spec's own
// wording for Join/Leave requests, without a precise number). Callers with
// a stricter operator-configured value should pass it directly to
// ValidateFreshness instead of this default.
const DefaultRequestFreshnessWindow = 5 * time.Minute

// IsRelayAuthoredKind reports whether kind is one of the event kinds this
// NIP requires to be signed by the relay's own "self" identity (NIP-11's
// `self` field) rather than by an arbitrary client: Role Definitions,
// Membership Lists, Add/Remove User, and Invite Request (the ephemeral
// response to a client's REQ for kind:28935, generated by the relay on
// demand).
func IsRelayAuthoredKind(kind int) bool {
	switch kind {
	case KindRoleDefinition, KindMembershipList, KindAddUser, KindRemoveUser, KindInviteRequest:
		return true
	default:
		return false
	}
}

// Failure modes, for callers that need to distinguish them (e.g. via
// errors.Is) rather than match on message text.
var (
	ErrWrongKind           = errors.New("nip43: wrong kind")
	ErrMissingProtectedTag = errors.New("nip43: missing NIP-70 protected tag")
	ErrMissingDTag         = errors.New("nip43: missing d tag (role id)")
	ErrInvalidColor        = errors.New("nip43: color must be an integer 0-360")
	ErrInvalidOrder        = errors.New("nip43: invalid order value")
	ErrInvalidMemberPubkey = errors.New("nip43: invalid member pubkey")
	ErrMissingPTag         = errors.New("nip43: missing p tag")
	ErrInvalidPubkey       = errors.New("nip43: invalid pubkey")
	ErrMissingClaimTag     = errors.New("nip43: missing claim tag")
	ErrStaleTimestamp      = errors.New("nip43: created_at is too far from now")
	ErrInvalidSignature    = errors.New("nip43: invalid signature")
)

// hasProtectedTag reports whether tags include a NIP-70 "-" tag: a
// single-element ["-"] tag marking the event as protected (publishable
// only by its own author). This package implements only this narrow
// presence check, not a general NIP-70 enforcement mechanism.
func hasProtectedTag(tags [][]string) bool {
	for _, tag := range tags {
		if len(tag) >= 1 && tag[0] == "-" {
			return true
		}
	}
	return false
}

// ValidateFreshness reports whether createdAt falls within window of now,
// per the spec's "created_at MUST be now, plus or minus a few minutes"
// requirement on Join and Leave requests.
func ValidateFreshness(createdAt uint64, now time.Time, window time.Duration) error {
	delta := int64(window.Seconds())
	nowUnix := now.Unix()
	if int64(createdAt) < nowUnix-delta || int64(createdAt) > nowUnix+delta {
		return ErrStaleTimestamp
	}
	return nil
}

// NewClaim generates a fresh, unpredictable invite-code claim string,
// mirroring nip42.NewChallenge()'s shape.
func NewClaim() string {
	return uuid.NewString()
}

/////////////////////////////////////////////////////////////////////
// Role Definitions (kind 33534)
/////////////////////////////////////////////////////////////////////

// Role is a parsed kind:33534 role-definition event. Color and Order are
// nil-able: the spec makes both optional, and 0 is a meaningful value for
// each (hue 0 red, order 0 first), so a bare int can't distinguish
// "unset" from "explicitly zero."
type Role struct {
	ID          string
	Label       string
	Description string
	Color       *int
	Order       *int
}

// ParseRole parses and structurally validates a kind:33534 event. It does
// not check that event.PubKey is actually the relay's configured "self"
// identity -- that is session/config-aware and lives in relay/, not here.
func ParseRole(event *nip01.Event) (*Role, error) {
	if event.Kind != KindRoleDefinition {
		return nil, fmt.Errorf("%w: got %d, want %d", ErrWrongKind, event.Kind, KindRoleDefinition)
	}
	if !hasProtectedTag(event.Tags) {
		return nil, ErrMissingProtectedTag
	}

	role := &Role{}
	haveD := false
	for _, tag := range event.Tags {
		if len(tag) < 2 {
			continue
		}
		switch tag[0] {
		case "d":
			role.ID = tag[1]
			haveD = true
		case "label":
			role.Label = tag[1]
		case "description":
			role.Description = tag[1]
		case "color":
			n, err := strconv.Atoi(tag[1])
			if err != nil || n < 0 || n > 360 {
				return nil, fmt.Errorf("%w: %q", ErrInvalidColor, tag[1])
			}
			role.Color = &n
		case "order":
			n, err := strconv.Atoi(tag[1])
			if err != nil {
				return nil, fmt.Errorf("%w: %q", ErrInvalidOrder, tag[1])
			}
			role.Order = &n
		}
	}
	if !haveD {
		return nil, ErrMissingDTag
	}
	return role, nil
}

// ValidateRole checks the signature and structure of a role-definition
// event.
func ValidateRole(event *nip01.Event) error {
	if err := event.Verify(); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidSignature, err)
	}
	_, err := ParseRole(event)
	return err
}

// RoleParams describes a NIP-43 role definition. SelfPubkey and ID are
// required; the rest are optional.
type RoleParams struct {
	SelfPubkey  string
	ID          string
	Label       string
	Description string
	Color       *int
	Order       *int
}

// NewRoleDefinition builds an unsigned kind:33534 event. Caller must sign
// it with the relay's own "self" private key.
func NewRoleDefinition(p RoleParams) *nip01.Event {
	tags := [][]string{{"-"}, {"d", p.ID}}
	if p.Label != "" {
		tags = append(tags, []string{"label", p.Label})
	}
	if p.Description != "" {
		tags = append(tags, []string{"description", p.Description})
	}
	if p.Color != nil {
		tags = append(tags, []string{"color", strconv.Itoa(*p.Color)})
	}
	if p.Order != nil {
		tags = append(tags, []string{"order", strconv.Itoa(*p.Order)})
	}
	return nip01.NewUnsignedEvent(KindRoleDefinition, p.SelfPubkey, "", tags...)
}

/////////////////////////////////////////////////////////////////////
// Membership Lists (kind 13534)
/////////////////////////////////////////////////////////////////////

// Member is one entry in a kind:13534 membership list: a pubkey plus any
// role ids assigned to it (the tag's arguments after the pubkey).
type Member struct {
	Pubkey string
	Roles  []string
}

// MembershipList is a parsed kind:13534 event. Per spec, this list "should
// not be considered exhaustive or authoritative" -- it is a best-effort
// advertisement of a relay's own internal, authoritative membership state,
// not the source of truth itself.
type MembershipList struct {
	Members []Member
}

// ParseMembershipList parses and structurally validates a kind:13534
// event. An empty member list is valid (e.g. a relay with no members
// enrolled yet).
func ParseMembershipList(event *nip01.Event) (*MembershipList, error) {
	if event.Kind != KindMembershipList {
		return nil, fmt.Errorf("%w: got %d, want %d", ErrWrongKind, event.Kind, KindMembershipList)
	}
	if !hasProtectedTag(event.Tags) {
		return nil, ErrMissingProtectedTag
	}

	list := &MembershipList{}
	for _, tag := range event.Tags {
		if len(tag) < 2 || tag[0] != "member" {
			continue
		}
		pubkey := tag[1]
		if err := utils.Validate32Key(pubkey); err != nil {
			return nil, fmt.Errorf("%w: %q: %v", ErrInvalidMemberPubkey, pubkey, err)
		}
		m := Member{Pubkey: pubkey}
		if len(tag) > 2 {
			m.Roles = append(m.Roles, tag[2:]...)
		}
		list.Members = append(list.Members, m)
	}
	return list, nil
}

// ValidateMembershipList checks the signature and structure of a
// membership-list event.
func ValidateMembershipList(event *nip01.Event) error {
	if err := event.Verify(); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidSignature, err)
	}
	_, err := ParseMembershipList(event)
	return err
}

// MembershipListParams describes a NIP-43 membership list.
type MembershipListParams struct {
	SelfPubkey string
	Members    []Member
}

// NewMembershipList builds an unsigned kind:13534 event. Caller must sign
// it with the relay's own "self" private key.
func NewMembershipList(p MembershipListParams) *nip01.Event {
	tags := [][]string{{"-"}}
	for _, m := range p.Members {
		tag := append([]string{"member", m.Pubkey}, m.Roles...)
		tags = append(tags, tag)
	}
	return nip01.NewUnsignedEvent(KindMembershipList, p.SelfPubkey, "", tags...)
}

/////////////////////////////////////////////////////////////////////
// Add User / Remove User (kind 8000 / 8001)
/////////////////////////////////////////////////////////////////////

// UserEvent is a parsed kind:8000 (add) or kind:8001 (remove) event.
type UserEvent struct {
	Kind   int
	Pubkey string
}

func parseUserEvent(event *nip01.Event, wantKind int) (*UserEvent, error) {
	if event.Kind != wantKind {
		return nil, fmt.Errorf("%w: got %d, want %d", ErrWrongKind, event.Kind, wantKind)
	}
	if !hasProtectedTag(event.Tags) {
		return nil, ErrMissingProtectedTag
	}
	pubkey, err := utils.FindUniqueEventTagValue(event.Tags, "p")
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrMissingPTag, err)
	}
	if err := utils.Validate32Key(pubkey); err != nil {
		return nil, fmt.Errorf("%w: %q: %v", ErrInvalidPubkey, pubkey, err)
	}
	return &UserEvent{Kind: wantKind, Pubkey: pubkey}, nil
}

// ParseAddUser parses and structurally validates a kind:8000 event.
func ParseAddUser(event *nip01.Event) (*UserEvent, error) {
	return parseUserEvent(event, KindAddUser)
}

// ParseRemoveUser parses and structurally validates a kind:8001 event.
func ParseRemoveUser(event *nip01.Event) (*UserEvent, error) {
	return parseUserEvent(event, KindRemoveUser)
}

// ValidateAddUser checks the signature and structure of an add-user event.
func ValidateAddUser(event *nip01.Event) error {
	if err := event.Verify(); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidSignature, err)
	}
	_, err := ParseAddUser(event)
	return err
}

// ValidateRemoveUser checks the signature and structure of a remove-user
// event.
func ValidateRemoveUser(event *nip01.Event) error {
	if err := event.Verify(); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidSignature, err)
	}
	_, err := ParseRemoveUser(event)
	return err
}

// NewAddUser builds an unsigned kind:8000 event. Caller must sign it with
// the relay's own "self" private key.
func NewAddUser(selfPubkey, memberPubkey string) *nip01.Event {
	return nip01.NewUnsignedEvent(KindAddUser, selfPubkey, "", []string{"-"}, []string{"p", memberPubkey})
}

// NewRemoveUser builds an unsigned kind:8001 event. Caller must sign it
// with the relay's own "self" private key.
func NewRemoveUser(selfPubkey, memberPubkey string) *nip01.Event {
	return nip01.NewUnsignedEvent(KindRemoveUser, selfPubkey, "", []string{"-"}, []string{"p", memberPubkey})
}

/////////////////////////////////////////////////////////////////////
// Join Request (kind 28934)
/////////////////////////////////////////////////////////////////////

// JoinRequest is a parsed kind:28934 event.
type JoinRequest struct {
	Claim string
}

// ParseJoinRequest parses and structurally validates a kind:28934 event.
// It does not check the created_at freshness window (see ValidateFreshness)
// or whether Claim is a currently valid invite code -- both require
// session/store context this pure package doesn't have.
func ParseJoinRequest(event *nip01.Event) (*JoinRequest, error) {
	if event.Kind != KindJoinRequest {
		return nil, fmt.Errorf("%w: got %d, want %d", ErrWrongKind, event.Kind, KindJoinRequest)
	}
	if !hasProtectedTag(event.Tags) {
		return nil, ErrMissingProtectedTag
	}
	claim, err := utils.FindUniqueEventTagValue(event.Tags, "claim")
	if err != nil || claim == "" {
		return nil, ErrMissingClaimTag
	}
	return &JoinRequest{Claim: claim}, nil
}

// NewJoinRequest builds an unsigned kind:28934 event. Caller must sign it
// with the joining user's own private key.
func NewJoinRequest(userPubkey, claim string) *nip01.Event {
	return nip01.NewUnsignedEvent(KindJoinRequest, userPubkey, "", []string{"-"}, []string{"claim", claim})
}

/////////////////////////////////////////////////////////////////////
// Invite Request (kind 28935)
/////////////////////////////////////////////////////////////////////

// InviteResponse is a parsed kind:28935 event: the relay's on-demand,
// per-request-generated response to a client's REQ for this kind.
type InviteResponse struct {
	Claim string
}

// ParseInviteResponse parses and structurally validates a kind:28935
// event.
func ParseInviteResponse(event *nip01.Event) (*InviteResponse, error) {
	if event.Kind != KindInviteRequest {
		return nil, fmt.Errorf("%w: got %d, want %d", ErrWrongKind, event.Kind, KindInviteRequest)
	}
	if !hasProtectedTag(event.Tags) {
		return nil, ErrMissingProtectedTag
	}
	claim, err := utils.FindUniqueEventTagValue(event.Tags, "claim")
	if err != nil || claim == "" {
		return nil, ErrMissingClaimTag
	}
	return &InviteResponse{Claim: claim}, nil
}

// ValidateInviteResponse checks the signature and structure of an
// invite-response event.
func ValidateInviteResponse(event *nip01.Event) error {
	if err := event.Verify(); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidSignature, err)
	}
	_, err := ParseInviteResponse(event)
	return err
}

// NewInviteResponse builds an unsigned kind:28935 event. Caller must sign
// it with the relay's own "self" private key.
func NewInviteResponse(selfPubkey, claim string) *nip01.Event {
	return nip01.NewUnsignedEvent(KindInviteRequest, selfPubkey, "", []string{"-"}, []string{"claim", claim})
}

/////////////////////////////////////////////////////////////////////
// Leave Request (kind 28936)
/////////////////////////////////////////////////////////////////////

// LeaveRequest is a parsed kind:28936 event. It carries no data beyond the
// NIP-70 protected tag -- the leaving pubkey is event.PubKey itself.
type LeaveRequest struct{}

// ParseLeaveRequest parses and structurally validates a kind:28936 event.
// It does not check the created_at freshness window -- see
// ValidateFreshness.
func ParseLeaveRequest(event *nip01.Event) (*LeaveRequest, error) {
	if event.Kind != KindLeaveRequest {
		return nil, fmt.Errorf("%w: got %d, want %d", ErrWrongKind, event.Kind, KindLeaveRequest)
	}
	if !hasProtectedTag(event.Tags) {
		return nil, ErrMissingProtectedTag
	}
	return &LeaveRequest{}, nil
}

// NewLeaveRequest builds an unsigned kind:28936 event. Caller must sign it
// with the leaving user's own private key.
func NewLeaveRequest(userPubkey string) *nip01.Event {
	return nip01.NewUnsignedEvent(KindLeaveRequest, userPubkey, "", []string{"-"})
}
